# Use the official Python 3.10 image
FROM python:3.10.13

# Set working directory inside container
WORKDIR /app

# Copy all project files into container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Command to start the app
CMD ["gunicorn", "main:app"]
